import type { Metadata } from "next";
import "./globals.css";
import Background from "./components/background/page";

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by Ahmed Allali",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="relative"
      >
         <Background />
        {children}
      </body>
    </html>
  );
}
